application:
  name: "cloud-ai-read-model"
  instance-id: "${random.uuid}"
  version: @project.version@
  cluster: local
caches:
  expire-seconds:
    active-tenant: 10
server:
  port: 9098
  error:
    include-message: always
    # # for local debugging
    # include-exception: true
    # include-stacktrace: always

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        specific.avro.reader: true
        key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    consumer:
      group-id: ${KAFKA_GROUP_ID}:${spring.application.name}-local
      auto-offset-reset: latest
      properties:
        schema.registry.url: http://localhost:8081
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      jdbcUrl: jdbc:postgresql://localhost:5432/cloud-ai-read-model
      username: cloud-ai-read-model
      password: cloud-ai-read-model
      data-source-properties:
        sslmode: disable
        sslfactory: org.postgresql.ssl.NonValidatingFactory
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    com.sap.fsm.springboot.starter.auth: DEBUG
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE

starter-management:
  security:
    enable: true
    username: test
    password: secret

starter-authentication:
  client-id: cloud-ai-read-model-qt

starter-feature-flag:
  enabled: false # override in local-qt-secrets.yaml to enable and provide sdk-key

starter-tenant-management:
  sync:
    enabled: false

starter-events:
  kafka:
    enabled: true
  monitoring:
    enabled: false
  mock-schema-registry-client: true

# This section includes all properties related to external service API calls
service:
  holiday:
    cache:
      metrics:
        enabled: false
      initial: 10
      max: 100
    timeoutInMs: 5000
  partner-dispatch:
    cache:
      metrics:
        enabled: false
      initial: 10
      max: 100

cloud-ai-read-model:
  kafka:
    technical-events.concurrency: ${KAFKA_TECHNICAL_EVENTS_CONCURRENCY:1}
    snapshot-events.concurrency: ${SNAPSHOT_EVENTS_CONCURRENCY:1}
