package com.bigitcompany.cloudaireadmodel.aggregation.domain.model;

public enum JobValidationError {
    DATA_MISMATCH ("DATA_MISMATCH"),
    ACTIVITY_MISSING_SERVICE_CALL("ACTIVITY_MISSING_SERVICE_CALL"),
    ACTIVITY_DURATION_CANNOT_BE_CALCULATED("ACTIVITY_DURATION_CANNOT_BE_CALCULATED"),
    ACTIVITY_MISSING_EARLIEST_START_DATE("ACTIVITY_MISSING_EARLIEST_START_DATE"),
    CURRENT_ASSIGNMENT_MISSING_START_OR_END_DATE("CURRENT_ASSIGNMENT_MISSING_START_OR_END_DATE");

    private String name;

    JobValidationError(String name) {
        this.name = name;
    }


}
